/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LmSlugRouteImport } from './routes/lm.$slug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as ApiPayfastCheckoutRouteImport } from './routes/api/payfast-checkout'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPreviewPipelineRouteImport } from './routes/_authenticated/preview-pipeline'
import { Route as AuthenticatedPdfGeneratorRouteImport } from './routes/_authenticated/pdf-generator'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLeadMagnetRouteImport } from './routes/_authenticated/lead-magnet'
import { Route as AuthenticatedFunnelsRouteImport } from './routes/_authenticated/funnels'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentSchedulerRouteImport } from './routes/_authenticated/content-scheduler'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiStudioRouteImport } from './routes/_authenticated/ai-studio'
import { Route as AuthenticatedFunnelsIdRouteImport } from './routes/_authenticated/funnels.$id'
import { Route as AuthenticatedFunnelsIdAnalyticsRouteImport } from './routes/_authenticated/funnels.$id.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LmSlugRoute = LmSlugRouteImport.update({
  id: '/lm/$slug',
  path: '/lm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayfastCheckoutRoute = ApiPayfastCheckoutRouteImport.update({
  id: '/api/payfast-checkout',
  path: '/api/payfast-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreviewPipelineRoute =
  AuthenticatedPreviewPipelineRouteImport.update({
    id: '/preview-pipeline',
    path: '/preview-pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPdfGeneratorRoute =
  AuthenticatedPdfGeneratorRouteImport.update({
    id: '/pdf-generator',
    path: '/pdf-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadMagnetRoute = AuthenticatedLeadMagnetRouteImport.update({
  id: '/lead-magnet',
  path: '/lead-magnet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFunnelsRoute = AuthenticatedFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentSchedulerRoute =
  AuthenticatedContentSchedulerRouteImport.update({
    id: '/content-scheduler',
    path: '/content-scheduler',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiStudioRoute = AuthenticatedAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFunnelsIdRoute = AuthenticatedFunnelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFunnelsRoute,
} as any)
const AuthenticatedFunnelsIdAnalyticsRoute =
  AuthenticatedFunnelsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedFunnelsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/content-scheduler': typeof AuthenticatedContentSchedulerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnels': typeof AuthenticatedFunnelsRouteWithChildren
  '/lead-magnet': typeof AuthenticatedLeadMagnetRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/pdf-generator': typeof AuthenticatedPdfGeneratorRoute
  '/preview-pipeline': typeof AuthenticatedPreviewPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/payfast-checkout': typeof ApiPayfastCheckoutRoute
  '/f/$slug': typeof FSlugRoute
  '/lm/$slug': typeof LmSlugRoute
  '/funnels/$id': typeof AuthenticatedFunnelsIdRouteWithChildren
  '/funnels/$id/analytics': typeof AuthenticatedFunnelsIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/content-scheduler': typeof AuthenticatedContentSchedulerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnels': typeof AuthenticatedFunnelsRouteWithChildren
  '/lead-magnet': typeof AuthenticatedLeadMagnetRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/pdf-generator': typeof AuthenticatedPdfGeneratorRoute
  '/preview-pipeline': typeof AuthenticatedPreviewPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/payfast-checkout': typeof ApiPayfastCheckoutRoute
  '/f/$slug': typeof FSlugRoute
  '/lm/$slug': typeof LmSlugRoute
  '/funnels/$id': typeof AuthenticatedFunnelsIdRouteWithChildren
  '/funnels/$id/analytics': typeof AuthenticatedFunnelsIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/ai-studio': typeof AuthenticatedAiStudioRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/content-scheduler': typeof AuthenticatedContentSchedulerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funnels': typeof AuthenticatedFunnelsRouteWithChildren
  '/_authenticated/lead-magnet': typeof AuthenticatedLeadMagnetRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/pdf-generator': typeof AuthenticatedPdfGeneratorRoute
  '/_authenticated/preview-pipeline': typeof AuthenticatedPreviewPipelineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/payfast-checkout': typeof ApiPayfastCheckoutRoute
  '/f/$slug': typeof FSlugRoute
  '/lm/$slug': typeof LmSlugRoute
  '/_authenticated/funnels/$id': typeof AuthenticatedFunnelsIdRouteWithChildren
  '/_authenticated/funnels/$id/analytics': typeof AuthenticatedFunnelsIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/ai-studio'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/content-scheduler'
    | '/dashboard'
    | '/funnels'
    | '/lead-magnet'
    | '/marketplace'
    | '/pdf-generator'
    | '/preview-pipeline'
    | '/settings'
    | '/api/payfast-checkout'
    | '/f/$slug'
    | '/lm/$slug'
    | '/funnels/$id'
    | '/funnels/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/ai-studio'
    | '/analytics'
    | '/automation'
    | '/billing'
    | '/content-scheduler'
    | '/dashboard'
    | '/funnels'
    | '/lead-magnet'
    | '/marketplace'
    | '/pdf-generator'
    | '/preview-pipeline'
    | '/settings'
    | '/api/payfast-checkout'
    | '/f/$slug'
    | '/lm/$slug'
    | '/funnels/$id'
    | '/funnels/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/ai-studio'
    | '/_authenticated/analytics'
    | '/_authenticated/automation'
    | '/_authenticated/billing'
    | '/_authenticated/content-scheduler'
    | '/_authenticated/dashboard'
    | '/_authenticated/funnels'
    | '/_authenticated/lead-magnet'
    | '/_authenticated/marketplace'
    | '/_authenticated/pdf-generator'
    | '/_authenticated/preview-pipeline'
    | '/_authenticated/settings'
    | '/api/payfast-checkout'
    | '/f/$slug'
    | '/lm/$slug'
    | '/_authenticated/funnels/$id'
    | '/_authenticated/funnels/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPayfastCheckoutRoute: typeof ApiPayfastCheckoutRoute
  FSlugRoute: typeof FSlugRoute
  LmSlugRoute: typeof LmSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lm/$slug': {
      id: '/lm/$slug'
      path: '/lm/$slug'
      fullPath: '/lm/$slug'
      preLoaderRoute: typeof LmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payfast-checkout': {
      id: '/api/payfast-checkout'
      path: '/api/payfast-checkout'
      fullPath: '/api/payfast-checkout'
      preLoaderRoute: typeof ApiPayfastCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preview-pipeline': {
      id: '/_authenticated/preview-pipeline'
      path: '/preview-pipeline'
      fullPath: '/preview-pipeline'
      preLoaderRoute: typeof AuthenticatedPreviewPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdf-generator': {
      id: '/_authenticated/pdf-generator'
      path: '/pdf-generator'
      fullPath: '/pdf-generator'
      preLoaderRoute: typeof AuthenticatedPdfGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead-magnet': {
      id: '/_authenticated/lead-magnet'
      path: '/lead-magnet'
      fullPath: '/lead-magnet'
      preLoaderRoute: typeof AuthenticatedLeadMagnetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funnels': {
      id: '/_authenticated/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof AuthenticatedFunnelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-scheduler': {
      id: '/_authenticated/content-scheduler'
      path: '/content-scheduler'
      fullPath: '/content-scheduler'
      preLoaderRoute: typeof AuthenticatedContentSchedulerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-studio': {
      id: '/_authenticated/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AuthenticatedAiStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funnels/$id': {
      id: '/_authenticated/funnels/$id'
      path: '/$id'
      fullPath: '/funnels/$id'
      preLoaderRoute: typeof AuthenticatedFunnelsIdRouteImport
      parentRoute: typeof AuthenticatedFunnelsRoute
    }
    '/_authenticated/funnels/$id/analytics': {
      id: '/_authenticated/funnels/$id/analytics'
      path: '/analytics'
      fullPath: '/funnels/$id/analytics'
      preLoaderRoute: typeof AuthenticatedFunnelsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedFunnelsIdRoute
    }
  }
}

interface AuthenticatedFunnelsIdRouteChildren {
  AuthenticatedFunnelsIdAnalyticsRoute: typeof AuthenticatedFunnelsIdAnalyticsRoute
}

const AuthenticatedFunnelsIdRouteChildren: AuthenticatedFunnelsIdRouteChildren =
  {
    AuthenticatedFunnelsIdAnalyticsRoute: AuthenticatedFunnelsIdAnalyticsRoute,
  }

const AuthenticatedFunnelsIdRouteWithChildren =
  AuthenticatedFunnelsIdRoute._addFileChildren(
    AuthenticatedFunnelsIdRouteChildren,
  )

interface AuthenticatedFunnelsRouteChildren {
  AuthenticatedFunnelsIdRoute: typeof AuthenticatedFunnelsIdRouteWithChildren
}

const AuthenticatedFunnelsRouteChildren: AuthenticatedFunnelsRouteChildren = {
  AuthenticatedFunnelsIdRoute: AuthenticatedFunnelsIdRouteWithChildren,
}

const AuthenticatedFunnelsRouteWithChildren =
  AuthenticatedFunnelsRoute._addFileChildren(AuthenticatedFunnelsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAiStudioRoute: typeof AuthenticatedAiStudioRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedContentSchedulerRoute: typeof AuthenticatedContentSchedulerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunnelsRoute: typeof AuthenticatedFunnelsRouteWithChildren
  AuthenticatedLeadMagnetRoute: typeof AuthenticatedLeadMagnetRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedPdfGeneratorRoute: typeof AuthenticatedPdfGeneratorRoute
  AuthenticatedPreviewPipelineRoute: typeof AuthenticatedPreviewPipelineRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiStudioRoute: AuthenticatedAiStudioRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedContentSchedulerRoute: AuthenticatedContentSchedulerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunnelsRoute: AuthenticatedFunnelsRouteWithChildren,
  AuthenticatedLeadMagnetRoute: AuthenticatedLeadMagnetRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedPdfGeneratorRoute: AuthenticatedPdfGeneratorRoute,
  AuthenticatedPreviewPipelineRoute: AuthenticatedPreviewPipelineRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPayfastCheckoutRoute: ApiPayfastCheckoutRoute,
  FSlugRoute: FSlugRoute,
  LmSlugRoute: LmSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
